# Generated by Django 3.1.6 on 2021-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
